name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Login to Docker Hub
        run: echo "${{ secrets.PASSWORD_SAI }}" | docker login -u "${{ secrets.USERNAME_SAI }}" --password-stdin

      - name: Build Docker Image
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          docker build -t sainath521/tax-filing-backend:$IMAGE_TAG .
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Publish Image to Docker Hub
        run: docker push sainath521/tax-filing-backend:$IMAGE_TAG

  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_SECRET_KEY }}

      - name: Deploy to EC2
        run: |
          IMAGE_TAG=${{ env.IMAGE_TAG }}
          ssh -o StrictHostKeyChecking=no ubuntu@13.229.92.87 << EOF
            sudo bash -c "
              echo 'Pulling the latest Docker image'
              docker pull sainath521/tax-filing-backend:$IMAGE_TAG

              echo 'Stopping and removing the old Docker container if exists'
              docker rm -f taxBackendContainer || true

              echo 'Running the new Docker container'
              docker run -d -p 4500:4500 --name taxBackendContainer sainath521/tax-filing-backend:$IMAGE_TAG

              echo 'Running containers after deployment:'
              docker ps

              echo 'Checking the latest image'
              docker images | grep tax-filing-backend
            "
          EOF
