import mongoose from "mongoose";

const companySchema = new mongoose.Schema({
  companyDetails: {
    companyName: { type: String },
    constitution: { type: String },
    clientStatus: { type: String },
    authorisedPerson: { type: String },
    phone: { type: String },
    mailId: { type: String },
  },
  incomeTax: {
    pan: { type: String },
    incomeTaxPassword: { type: String },
    status: { type: String },
    effectiveFrom: { type: Date },
    effectiveTo: { type: Date },
  },
  gst: {
    gstin: { type: String },
    gstUserName: { type: String },
    gstPassword: { type: String },
    gstStatus: { type: String },
    eWayBillUsername: { type: String },
    eWayBillPassword: { type: String },
    effectiveFrom: { type: Date },
    effectiveTo: { type: Date },
  },
  esi: {
    esiNumber: { type: String },
    esiUserId: { type: String },
    esiPassword: { type: String },
    status: { type: String },
    effectiveFrom: { type: Date },
    effectiveTo: { type: Date },
  },
  providentFund: {
    pfNumber: { type: String },
    pfUserId: { type: String },
    pfPassword: { type: String },
    status: { type: String },
    effectiveFrom: { type: Date },
    effectiveTo: { type: Date },
  },
  professionalTax: {
    ptEcNumber: { type: String },
    ptUsername: { type: String },
    ptPassword: { type: String },
    ptNumber: { type: String },
    status: { type: String },
    effectiveFrom: { type: Date },
    effectiveTo: { type: Date },
  },
  tds: {
    tan: { type: String },
    tanPassword: { type: String },
    tracesUsername: { type: String },
    tracesPassword: { type: String },
    status: { type: String },
    effectiveFrom: { type: Date },
    effectiveTo: { type: Date },
  },
  shopCommercialEstablishment: {
    seNumber: { type: String },
    seUsername: { type: String },
    sePassword: { type: String },
    seRenewalDate: { type: Date },
    status: { type: String },
    effectiveFrom: { type: Date },
    effectiveTo: { type: Date },
  },
  msme: {
    msmeNumber: { type: String },
    status: { type: String },
    effectiveFrom: { type: Date },
    effectiveTo: { type: Date },
  },
  fssai: {
    fssaiNumber: { type: String },
    fssaiUsername: { type: String },
    fssaiPassword: { type: String },
    fssaiRenewalDate: { type: Date },
    status: { type: String },
    effectiveFrom: { type: Date },
    effectiveTo: { type: Date },
  },
  factoryLicense: {
    flNumber: { type: String },
    flUsername: { type: String },
    flPassword: { type: String },
    flRenewalDate: { type: Date },
    status: { type: String },
    effectiveFrom: { type: Date },
    effectiveTo: { type: Date },
  },
  importExport: {
    iecNumber: { type: String },
    dgftUsername: { type: String },
    dgftPassword: { type: String },
    icegateUsername: { type: String },
    icegatePassword: { type: String },
    status: { type: String },
    effectiveFrom: { type: Date },
    effectiveTo: { type: Date },
  },
  partnershipFirmFormC: {
    formCNumber: { type: String },
    status: { type: String },
    effectiveFrom: { type: Date },
    effectiveTo: { type: Date },
  },
  shramSuvidhaPortal: {
    lin: { type: String },
    ssUsername: { type: String },
    ssPassword: { type: String },
    status: { type: String },
    effectiveFrom: { type: Date },
    effectiveTo: { type: Date },
  },
  mca: {
    cin: { type: String },
    mcaUsername: { type: String },
    mcaPassword: { type: String },
    bankOverdraftCashCreditRenewalDate: { type: Date },
    status: { type: String },
    effectiveFrom: { type: Date },
    effectiveTo: { type: Date },
  },
  attachments: {
    panFile: { type: String },
    gstFile: { type: String },
    esiFile: { type: String },
    pfFile: { type: String },
    ptFile: { type: String },
    tanFile: { type: String },
    shopEstablishmentFile: { type: String },
    msmeFile: { type: String },
    fssaiFile: { type: String },
    factoryLicenseFile: { type: String },
    importExportFile: { type: String },
    partnershipFormcFile: { type: String },
    shramSuvidhaFile: { type: String },
    mcaFile: { type: String },
    cinFile: { type: String },
  },
});

const companyModel = mongoose.model("Company", companySchema);
export default companyModel;
